### ISSUE TITLE
TCP/IP protocol 

### ISSUE THREAD

**Issue by Changliu52** [bmegli/minimal-latency-streaming-protocol#9]
Hi @bmegli ,

Wondering if there is an example using TCP instead of UDP? To minimise packets lose.

I guess it’s a matter of changing this line? https://github.com/bmegli/minimal-latency-streaming-protocol/blob/9b386c12195bd134369111245f2a1f95a903779f/mlsp.c#L82

Please recommend the best practice.

Best Regards,
Chang

**Comment by bmegli** [comment]
Hi @Changliu52,

There is no such example. I have no plans to implement TCP/IP in this library.

> I guess it’s a matter of changing this line? 

It is a lot more complex than that. It is connection vs connection-less logic.

In TCP/IP you would have to implement logic for waiting for client, accepting connections, managing connections (disconnects, maybe dealing with stale connections). 

The start would be a sequence of `socket`, `bind`, `listen`, `accept` functions on server side.\
The client would  use `socket` and `connect`.

This somehow escalates to application level (should you start processing data before connection? What to do on disconnect? Reconnect? Terminate? What to do if client can't connect to the server? Try reconnecting, fail?).

If you want to implement it start by examining some unix/linux socket tutorial code (generally short code).

Once you know what you want to do (application level logic, what should really happen, who waits, when processing begins, what happens on disconnects, etc) you would have to implement it.

You could also start with simple logic.

Also it is not obvious who is the server and who is the client. Both options make sense:
- client connects to server and pushes the data
- client connects to server that serves him data stream

**Comment by Changliu52** [comment]
Thank you for the information. I will close this for now. and will reopen if we decided to go down this route.
